name: bitchat
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cupertino_list_tile: ^0.2.1
  page_transition: ^2.0.9
  swipeable_button_view: ^0.0.2
  url_launcher: ^6.1.6
  get: ^4.6.5
  http: ^0.13.5
  country_picker: ^2.0.16
  flutter_localizations:
   sdk: flutter
  extended_phone_number_input: ^1.0.2
  intl_phone_field: ^3.1.0
  pinput: ^2.2.16
  dio: ^4.0.6
  flutter_svg: ^1.1.6
  carousel_slider: ^4.0.0
  story_view: ^0.14.0
  dashed_circle: ^0.0.2
 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - images/bg.jpeg
    - images/whatsapp.png
    - images/login.png
    - images/otpui.png
    - images/bijakLogo.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

